apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jeffrey-botterhill.fullname" . }}
  labels:
    gitsha: {{ .Values.gitsha }}
    {{- include "jeffrey-botterhill.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jeffrey-botterhill.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jeffrey-botterhill.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jeffrey-botterhill.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include ".Values.env" . | nindent 12 }}
            - name: GIT_SHA
              value: {{ .Values.gitsha }}
            - name: RAILS_LOG_TO_STDOUT
              value: {{ .Values.logToStdout | quote }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "jeffrey-botterhill.fullname" . }}
                  key: secretKeyBase
            - name: RACK_ENV
              value:  {{ .Values.environment | upper | quote}}
            - name: RAILS_ENV
              value:  {{ .Values.environment | upper | quote}}
            - name: SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "jeffrey-botterhill.fullname" . }}
                  key: slackToken
            - name: DATABASE_URL
              value: {{ .Values.databaseURL }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
