apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jeffrey-botterhill.fullname" . }}
  labels:
  {{- include "jeffrey-botterhill.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.secretKeyBase }}
  secretKeyBase: {{ randAlphaNum 16 | sha256sum | b64enc | quote }}
  {{- else }}
  secretKeyBase: {{ .Values.secretKeyBase | b64enc | quote }}
  {{- end }}
  slackToken: {{ .Values.slackToken | b64enc | quote }}

